### ISSUE TITLE
ToolsUpdater.sh script on Mac

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/WPILibInstaller#11]
_From @bradamiller on October 28, 2018 16:34_

The line endings are in dos format on ToolsUpdater.sh on mac after decompressing and untaring the file. dos2unix is not available on macs by default. Also, realpath is missing. Rumor is we're considering switching to python or ruby. The installed versions with Mojave are:

python 2.7 (installed by default and you can get 3 with homebrew)
and ruby 2.3.7

_Copied from original issue: wpilibsuite/vscode-wpilib#116_

**Comment by ThadHouse** [comment]
This was replaced by the python script, so this should be fixed.
