### ISSUE TITLE
Add shortcuts to all accounts when installing to all users

### ISSUE THREAD

**Issue by Aric5301** [wpilibsuite/WPILibInstaller#41]
Hi!
I recently installed the 2019 WPILib libraries on a Windows 64bit machine. I installed it using a non-admin account. For some reason, I was not able to find any shortcuts on the desktop. I also tried searching for the software in the start menu but with no success.
When I logged in using the admin account, all the shortcuts were there on the desktop.

P.S. It happened twice, on both a Windows 10 and a Windows 7 machine.

Thanks!

Aric Radzin,
Team Captain and Lead Programmer,
BumbleB 3339.

**Comment by Aric5301** [comment]
![whatsapp image 2019-01-06 at 18 05 32](https://user-images.githubusercontent.com/25414752/50738540-c611a300-11dd-11e9-883b-8875ecda862d.jpeg)

Update:
I just noticed that by searching "frc" in the Start search menu I can access the program from the non-admin account. Still, no logo and no desktop shortcuts created for either program (VS Code, Shuffleboard, etc..).

**Comment by ThadHouse** [comment]
Did you run the installer as all users or did you ever elevate the process with a UAC prompt? All users only puts the shortcuts on the admin account which is probably a bug we should fix but that's what happens there.

**Comment by Aric5301** [comment]
> Did you run the installer as all users or did you ever elevate the process with a UAC prompt? All users only puts the shortcuts on the admin account which is probably a bug we should fix but that's what happens there.

I ran the installer as "all users", and indeed elevated it with a UAC prompt.
I think that it will be better if "all users" would place shortcuts in all users, or at least in both the admin and the user which the installer was run on.

Thanks for the quick reply!

**Comment by ThadHouse** [comment]
Ah ok. Yeah we've mostly focused on the user install, so I forgot to test. Everything installs to c:\users\public\frc2019, so you can access that from your account and create shortcuts. 

It was an oversight on our side, we will fix that.
