### ISSUE TITLE
Downloading VS Code without internet throws an Unhandled exception

### ISSUE THREAD

**Issue by KeithRieck** [wpilibsuite/WPILibInstaller#5]
If there is not internet connection and I push the button for "Select/Download VS Code" and then the "Download" button,  I get an Unhandled exception dialog, saying "The remote name could not be resolved for vscode-update.asurewebsites.net".

OK, it's easy to figure out why I'm getting this error dialog, but maybe you should put up a different message.

**Comment by ThadHouse** [comment]
Thanks! I'll fix this.
