### ISSUE TITLE
Searching Documentation (in ~/frc2019/documentation/java) returns 404

### ISSUE THREAD

**Issue by alan412** [wpilibsuite/WPILibInstaller#50]
When you search documentation (by opening ~/frc2019/documentation/java/index.html in Chrome on a mac), you get (for example searching on Victor): 
file:///Users/xxxxxxx/frc2019/documentation/java/undefined/edu/wpi/first/wpilibj/Victor.html

You should get:
file:///Users/xxxxxxx/frc2019/documentation/java/edu/wpi/first/wpilibj/Victor.html

Obviously a minor problem, but still a pain....

**Comment by ThadHouse** [comment]
Transfered to the installer, since that is where the docs are located.

**Comment by ThadHouse** [comment]
It's actually an issue in the generation starting with java 11. There is an open pr to fix the issue in allwpilib
