### ISSUE TITLE
Wrong version in file name of 2019.3.2 installer

### ISSUE THREAD

**Issue by Aric5301** [wpilibsuite/WPILibInstaller#52]
The installer inside the zip file of the 64bit Windows installer (_WPILibInstaller_Windows64-2019.3.2.zip_) is named _WPILibInstaller_Full-Windows64-2019.1.1.exe_. I did not try to install it using the installer so I don't know which version really gets installed.

**Comment by ThadHouse** [comment]
https://github.com/wpilibsuite/allwpilib/issues/1602#issuecomment-464167040

See here, it is the right version, just the internal name wasn't updated.
